import DOMPurify from 'dompurify'
import { renderMarkdown } from './markdown.js'
import { initChat } from './chat.js'

const $=id=>document.getElementById(id), base=document.body.dataset.base
const S={draft:null,dirty:false,saving:null,tab:'local',page:1,mode:'ai',view:'split',job:null,identity:null,attachments:[],selected:new Set(),prepared:null,metadataReady:false}
let saveTimer,pollTimer,searchTimer,cursor={start:0,end:0}
const content=()=>({title:$('title').value,text:$('text').value,slug:$('slug').value,format:S.draft.format,tags:$('tags').value.split(/[,，]/).map(v=>v.trim()).filter(Boolean),categories:S.metadataReady?[...$('categories').selectedOptions].map(v=>Number(v.value)):S.draft.categories})
const safeURL=value=>{try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)?u.href:null}catch{return null}}
function notice(error,target='notice'){const el=$(target);el.textContent=error?.message??String(error);el.hidden=false;el.focus()}
function clearNotice(){$('notice').hidden=true}
async function request(path,options={}){const r=await fetch(base+path,{credentials:'same-origin',...options});let data;try{data=await r.json()}catch{throw new Error('服务返回异常，请检查登录状态')}if(!r.ok)throw new Error(data.error??data.message??`请求失败（${r.status}）`);return data}
const api=(action,args={})=>request('/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,args})})
const action=(fn,target='notice')=>async e=>{try{clearNotice();await fn(e)}catch(err){notice(err,target)}}
function render(){if(!S.draft)return;$('word-count').textContent=`${$('text').value.length.toLocaleString()} 字符`;$('preview').innerHTML=S.draft.format==='html'?DOMPurify.sanitize($('text').value,{USE_PROFILES:{html:true}}):renderMarkdown($('text').value)}
function changed(){if(!S.draft)return;S.dirty=true;$('save-state').textContent='有未保存修改';render();clearTimeout(saveTimer);saveTimer=setTimeout(()=>flush().catch(notice),900)}
async function flush(){
  clearTimeout(saveTimer)
  if(S.saving)return S.saving
  S.saving=(async()=>{while(S.dirty&&S.draft){const id=S.draft.id,payload=content();$('save-state').textContent='保存中…';const result=await api('save',{id,revision:S.draft.revision,content:payload});if(S.draft?.id!==id)return;S.draft=result;S.dirty=JSON.stringify(payload)!==JSON.stringify(content());$('save-state').textContent=S.dirty?'还有修改待保存':'已保存';showProposal()}})()
  try{await S.saving;await loadList()}catch(err){$('save-state').textContent='保存失败 · 内容仍在编辑器';throw err}finally{S.saving=null}
}
function fill(draft){S.draft=draft;S.dirty=false;$('empty').hidden=true;$('editor').hidden=false;for(const key of ['title','text','slug'])$(key).value=draft[key];$('tags').value=draft.tags.join('，');for(const option of $('categories').options)option.selected=draft.categories.includes(Number(option.value));$('format-label').textContent=draft.format==='html'?'HTML 原文 · 原格式保留':'Markdown 原文';$('save-state').textContent='已保存';$('answer').innerHTML='';$('task-state').textContent='';S.job=null;clearTimeout(pollTimer);render();showProposal();sessionStorage.setItem(`blog-draft:${S.identity.userId}`,draft.id);$('library').classList.remove('open')}
async function openDraft(id){await flush();fill(await api('draft',{id}));await Promise.all([loadAttachments(),loadTasks(),loadOperations()]);await loadList()}
async function createDraft(){await flush();fill(await api('create'));S.attachments=[];S.selected.clear();showAttachments();await loadList()}
async function loadList(){const list=$('article-list');list.replaceChildren();$('more-articles').hidden=true;const query=$('search').value.trim();let items
  if(S.tab==='local')items=await api('drafts',{query})
  else{const result=await api('articles',{query,page:S.page});items=result.items;$('more-articles').hidden=!result.hasMore}
  for(const d of items){const button=document.createElement('button');button.className=`article-row ${S.draft?.id===d.id?'active':''}`;const title=document.createElement('span');title.textContent=d.title||'未命名草稿';const small=document.createElement('small');small.textContent=S.tab==='local'?new Date(d.updatedAt).toLocaleString('zh-CN'):`${d.hasPublished?'已发布':'草稿'}${d.hasSavedDraft?' · 有保存稿':''}`;button.append(title,small);button.addEventListener('click',action(async()=>{if(S.tab==='local')await openDraft(d.id);else{await flush();const imported=await api('import',{cid:d.cid,variant:d.hasSavedDraft&&!d.hasPublished?'savedDraft':'published'});S.tab='local';tabs();fill(imported);await Promise.all([loadAttachments(),loadOperations(),loadList()])}}));list.append(button)
    if(S.tab==='remote'&&d.hasPublished&&d.hasSavedDraft){const saved=document.createElement('button');saved.textContent='导入该文的保存稿';saved.className='article-row';saved.addEventListener('click',action(async()=>{await flush();const imported=await api('import',{cid:d.cid,variant:'savedDraft'});S.tab='local';tabs();fill(imported);await Promise.all([loadList(),loadAttachments(),loadOperations()])}));list.append(saved)}}
  if(!items.length){const p=document.createElement('p');p.className='muted';p.textContent='还没有匹配的文章';list.append(p)}
}
function tabs(){for(const t of ['local','remote'])$(`${t}-tab`).setAttribute('aria-pressed',String(S.tab===t))}
function mode(value){S.mode=value;document.querySelector('.workspace').classList.toggle('manual',value==='manual');$('mode-ai').setAttribute('aria-pressed',String(value==='ai'));$('mode-manual').setAttribute('aria-pressed',String(value==='manual'))}
function insert(text){if(!S.draft)throw new Error('请先新建或选择草稿');const area=$('text');area.focus();area.setSelectionRange(cursor.start,cursor.end);area.setRangeText(text,cursor.start,cursor.end,'end');cursor={start:area.selectionStart,end:area.selectionEnd};changed()}
function showSources(sources=[]){const box=$('sources');box.replaceChildren();for(const s of sources){const item=document.createElement('div');item.className='source';const url=safeURL(s.url);const title=document.createElement(url?'a':'span');title.textContent=s.title||s.url;if(url){title.href=url;title.target='_blank';title.rel='noopener noreferrer'}const meta=document.createElement('small');meta.textContent=`${s.fetched?'已抓取原文':'仅搜索摘要'} · ${s.retrievedAt?new Date(s.retrievedAt).toLocaleString('zh-CN'):''}${s.publishedAt?' · 发布于 '+s.publishedAt:''}`;item.append(title,meta);box.append(item)}if(!sources.length){const p=document.createElement('p');p.className='muted';p.textContent='尚无查证来源';box.append(p)}}
function showProposal(){const p=S.draft?.proposal;$('proposal').hidden=!p;if(!p)return;$('proposal-text').textContent=`${p.fields.title}\n\n${p.fields.text}\n\n标签：${p.fields.tags.join('、')}`;const conflict=p.baseRevision!==S.draft.revision;$('proposal-conflict').hidden=!conflict;$('apply-proposal').disabled=conflict;showSources(p.sources)}
async function loadTasks(){if(!S.draft)return;const jobs=await api('tasks',{draftId:S.draft.id});if(jobs.length){S.job=jobs[0];showJob();if(['queued','running'].includes(S.job.status))poll()}}
function showJob(){const j=S.job;if(!j)return;const busy=['queued','running'].includes(j.status);$('ask').disabled=busy;$('cancel-task').hidden=!busy;const names={queued:'等待开始',running:'正在整理与写作',succeeded:'本次写作完成',failed:'本次写作未完成',cancelled:'已停止'};$('task-state').textContent=`${names[j.status]??j.status}${j.error?' · '+j.error.message:''}${j.input.research&&!j.sources.some(s=>s.fetched)?' · 未完成原文查证':''}`;$('answer').innerHTML=renderMarkdown(j.text||'');showSources(j.sources)}
async function poll(){clearTimeout(pollTimer);const id=S.job?.id;if(!id)return;try{const j=await api('task',{id});if(S.job?.id!==id)return;S.job=j;showJob();if(['queued','running'].includes(j.status))pollTimer=setTimeout(poll,900);else if(S.draft){const d=await api('draft',{id:S.draft.id});if(S.draft?.id===d.id){S.draft.proposal=d.proposal;showProposal()}}}catch(err){notice(err);$('ask').disabled=false}}
async function loadOperations(){if(!S.draft)return;const rows=await api('operations',{draftId:S.draft.id});const box=$('operations');box.replaceChildren();for(const op of rows){const item=document.createElement('div');const status={prepared:'等待确认',running:'提交中',uncertain:'结果待核对',succeeded:'已确认成功',conflict:'版本冲突'};item.textContent=`${op.mode==='publish'?'发布/更新':'同步草稿'} · ${status[op.status]??op.status}`;if(safeURL(op.url)){const link=document.createElement('a');link.href=safeURL(op.url);link.target='_blank';link.rel='noopener';link.textContent=' 查看文章 ↗';item.append(link)}if(['running','uncertain'].includes(op.status)){const b=document.createElement('button');b.textContent='核对回执';b.addEventListener('click',action(async()=>{const r=await api('reconcile',{id:op.id});if(r.status==='uncertain')notice(r.message);await loadOperations()}));item.append(b)}box.append(item)}}
async function prepare(mode){await flush();if(!S.draft)throw new Error('请先选择草稿');S.prepared=await api('prepare',{id:S.draft.id,revision:S.draft.revision,mode});$('publish-error').hidden=true;$('publish-heading').textContent=mode==='publish'?'确认发布 / 更新公开文章':'确认同步博客草稿';$('publish-description').textContent=`《${S.prepared.title}》 · 本地保存不会自动发布，请核对以下内容。`;$('before-text').textContent=S.prepared.before?`${S.prepared.before.title}\n\n${S.prepared.before.text}`:'尚无公开版本';$('after-text').textContent=`${S.prepared.after.title}\n\n${S.prepared.after.text}\n\n标签：${S.prepared.after.tags.join('、')}`;$('consume-label').hidden=!(mode==='publish'&&S.prepared.hasSavedDraft);$('consume-draft').checked=false;$('publish-dialog').showModal()}
async function loadAttachments(){if(!S.draft)return;S.attachments=await api('attachments',{draftId:S.draft.id});S.selected=new Set(S.attachments.filter(a=>a.selected!==false&&a.status==='ready').map(a=>a.id));showAttachments()}
function showAttachments(){const box=$('attachment-list');box.replaceChildren();for(const a of S.attachments){
  const row=document.createElement('div');row.className='attachment-row';const check=document.createElement('input');check.type='checkbox';check.checked=S.selected.has(a.id);check.disabled=a.status!=='ready'||(a.partial&&!a.range);check.setAttribute('aria-label',`本次阅读 ${a.name}`)
  check.addEventListener('change',action(async()=>{await api('attachment-select',{draftId:S.draft.id,id:a.id,selected:check.checked,range:a.range});await loadAttachments()}))
  const label=document.createElement('span');label.textContent=`${a.name} · ${a.status==='ready'?(a.partial?'部分解析':a.characters?`${a.characters} 字符`:'图片可阅读'):a.message||a.status}${a.range?` · ${a.range.from}–${a.range.to} ${a.unit}`:''}`
  const view=document.createElement('button');view.textContent='查看';view.disabled=a.status!=='ready';view.addEventListener('click',action(()=>viewAttachment(a),'attachment-error'))
  const remove=document.createElement('button');remove.textContent='移除';remove.addEventListener('click',action(async()=>{await api('attachment-remove',{draftId:S.draft.id,id:a.id});await loadAttachments()}));row.append(check,label,view,remove);box.append(row)
}}
async function viewAttachment(a){
  S.attachmentView={draftId:S.draft.id,id:a.id};$('attachment-dialog').showModal();$('attachment-error').hidden=true;$('attachment-image').hidden=true;$('attachment-image').removeAttribute('src');$('attachment-text').textContent='加载中…'
  const data=await api('attachment-content',S.attachmentView);$('attachment-title').textContent=data.name;$('attachment-description').textContent=data.message||`已提取 ${data.parsedUnits}/${data.totalUnits} ${data.unit}，共 ${data.characters} 字符`;$('attachment-text').textContent=data.units.map(u=>`[${data.unit} ${u.number}] ${u.text}`).join('\n');$('attachment-range').hidden=!data.units.length;$('range-from').value=data.range?.from??1;$('range-to').value=data.range?.to??data.parsedUnits
  const url=`${base}/attachment-download?draftId=${encodeURIComponent(S.attachmentView.draftId)}&id=${encodeURIComponent(a.id)}`;$('attachment-download').href=url
  if(data.kind.startsWith('image/')){$('attachment-image').src=url+'&inline=1';$('attachment-image').hidden=false}
}
async function loadBackups(){const d=await api('backup-status');$('backup-enabled').checked=d.schedule.enabled;$('backup-time').value=d.schedule.time;$('backup-daily').value=d.schedule.daily;$('backup-weekly').value=d.schedule.weekly;
  const labels={running:'进行中',succeeded:'已完成',failed:'失败',complete:'完整',writing:'写入中'}
  $('backup-status').textContent=`下次计划：${d.nextRun||'未启用'}\n当前：${labels[d.current?.status]??'空闲'} ${d.current?.message??d.current?.note??''}\n最近：${d.last?.id??d.last?.backupId??'暂无'} · ${labels[d.last?.status]??''}${d.recoveryPending?'\n服务恢复尚未确认，请检查运维状态':''}`
  const box=$('backup-list');box.replaceChildren();for(const b of d.backups??[]){const row=document.createElement('div');row.className='operations';row.textContent=`${b.id} · ${labels[b.status]??b.status} `;const verify=document.createElement('button');verify.textContent='校验';verify.addEventListener('click',action(async()=>{const r=await api('backup-verify',{id:b.id});$('backup-status').textContent=`${r.id}：${r.components} 个组件校验通过`},'backup-error'));row.append(verify)
    for(const [mode,label] of [['isolated','隔离恢复演练'],['production','恢复到生产']]){const button=document.createElement('button');button.textContent=label;button.disabled=b.status!=='complete';button.addEventListener('click',action(async()=>{S.restore=await api('backup-restore-prepare',{id:b.id,mode});$('restore-title').textContent=label;$('restore-description').textContent=mode==='production'?'将先备份当前状态，再恢复所选博客版本、工作台草稿和 pelyblog 图片。过程会短暂停止相关服务；原目录与数据库会保留。其他图床策略不会被覆盖。':'将备份还原到独立目录与数据库，核验文件和数据。不会覆盖生产网站。';$('restore-id').textContent=b.id;$('restore-check').value='';$('restore-error').hidden=true;$('restore-dialog').showModal()},'backup-error'));row.append(button)}box.append(row)
  }
}

for(const id of ['title','text','slug','tags','categories'])$(id).addEventListener('input',changed)
for(const event of ['keyup','mouseup','select','blur'])$('text').addEventListener(event,()=>{cursor={start:$('text').selectionStart,end:$('text').selectionEnd}})
$('new-draft').addEventListener('click',action(createDraft));$('empty-new').addEventListener('click',action(createDraft));$('save').addEventListener('click',action(flush))
$('mode-ai').addEventListener('click',()=>mode('ai'));$('mode-manual').addEventListener('click',()=>mode('manual'))
for(const b of document.querySelectorAll('[data-view]'))b.addEventListener('click',()=>{S.view=b.dataset.view;$('document').className=`document ${S.view}`;for(const el of document.querySelectorAll('[data-view]'))el.setAttribute('aria-pressed',String(el===b))})
for(const b of document.querySelectorAll('[data-insert]'))b.addEventListener('click',action(()=>{if(S.draft?.format==='html')throw new Error('当前是 HTML 原文，请直接编辑标签，避免隐式转换格式');const selected=$('text').value.slice(cursor.start,cursor.end);insert({heading:'\n## '+(selected||'小标题')+'\n',bold:'**'+(selected||'重点')+'**',italic:'*'+(selected||'文字')+'*',code:'\n```text\n'+(selected||'代码')+'\n```\n',link:'['+(selected||'链接文字')+'](https://)',list:'\n- '+(selected||'列表项')+'\n'}[b.dataset.insert])}))
for(const tab of ['local','remote'])$(`${tab}-tab`).addEventListener('click',action(async()=>{S.tab=tab;S.page=1;tabs();await loadList()}))
$('search').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{S.page=1;loadList().catch(notice)},300)})
$('more-articles').addEventListener('click',action(async()=>{S.page++;await loadList()}));$('library-toggle').addEventListener('click',()=>$('library').classList.toggle('open'))
$('insert-image').addEventListener('click',()=>{if(S.draft)$('image-file').click();else notice('请先选择草稿')})
$('image-file').addEventListener('change',action(async()=>{const file=$('image-file').files[0];if(!file)return;const draftId=S.draft.id;const r=await request('/upload',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});if(S.draft?.id!==draftId)throw new Error('图片上传成功，但草稿已切换，请回原草稿插入');insert(S.draft.format==='html'?`<img src="${r.url.replaceAll('"','&quot;')}" alt="">`:`\n![图片说明](${r.url})\n`);$('image-file').value=''}))
$('ask').addEventListener('click',action(async()=>{await flush();if(!S.draft)throw new Error('请先新建或选择草稿');S.job=await api('task-start',{requestId:crypto.randomUUID(),draftId:S.draft.id,expectedRevision:S.draft.revision,instruction:$('instruction').value,research:$('research').checked,attachments:S.attachments.filter(a=>S.selected.has(a.id)).map(a=>({id:a.id,version:a.version,range:a.range}))});showJob();poll()}))
$('cancel-task').addEventListener('click',action(async()=>{if(S.job){S.job=await api('task-cancel',{id:S.job.id});showJob()}}))
$('apply-proposal').addEventListener('click',action(async()=>{await flush();const d=await api('apply',{id:S.draft.id,revision:S.draft.revision,proposalId:S.draft.proposal.id,fields:[...document.querySelectorAll('[name=apply-field]:checked')].map(v=>v.value)});fill(d);await loadList()}))
$('insert-proposal').addEventListener('click',action(()=>insert(S.draft.proposal.fields.text)))
$('sync-draft').addEventListener('click',action(()=>prepare('draft')));$('publish').addEventListener('click',action(()=>prepare('publish')))
for(const b of document.querySelectorAll('[data-close]'))b.addEventListener('click',()=>$(b.dataset.close).close())
$('confirm-publish').addEventListener('click',action(async()=>{$('confirm-publish').disabled=true;try{await api('confirm',{id:S.prepared.id,nonce:S.prepared.nonce,consumeSavedDraft:$('consume-draft').checked});$('publish-dialog').close();await openDraft(S.draft.id)}finally{$('confirm-publish').disabled=false;await loadOperations()}},'publish-error'))
$('attachment-add').addEventListener('click',()=>{if(S.draft)$('attachment-files').click();else notice('请先新建或选择草稿')})
$('attachment-files').addEventListener('change',action(async()=>{await flush();const draftId=S.draft.id;$('attachment-add').disabled=true;try{for(const file of $('attachment-files').files){if(file.size>20*1024*1024)throw new Error('单文件不能超过 20 MiB');$('attachment-add').textContent='资料处理中…';await request(`/attachment?draftId=${encodeURIComponent(draftId)}&name=${encodeURIComponent(file.name)}`,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file})}}finally{if(S.draft?.id===draftId)await loadAttachments();$('attachment-files').value='';$('attachment-add').disabled=false;$('attachment-add').textContent='＋ 添加资料'}}))
$('range-save').addEventListener('click',action(async()=>{await api('attachment-select',{...S.attachmentView,selected:true,range:{from:Number($('range-from').value),to:Number($('range-to').value)}});await loadAttachments();$('attachment-dialog').close()},'attachment-error'))
$('backup-open').addEventListener('click',action(async()=>{$('backup-dialog').showModal();await loadBackups()},'backup-error'))
$('backup-refresh').addEventListener('click',action(loadBackups,'backup-error'))
$('backup-run').addEventListener('click',action(async()=>{await api('backup-run');await loadBackups()},'backup-error'))
$('restore-confirm').addEventListener('click',action(async()=>{if($('restore-check').value!==S.restore.backupId)throw new Error('请输入与所选版本一致的完整备份标识');$('restore-confirm').disabled=true;try{await api('backup-restore-confirm',{id:S.restore.id,nonce:S.restore.nonce,backupId:S.restore.backupId});$('restore-dialog').close();$('backup-status').textContent='恢复任务已提交，点击刷新查看状态；生产恢复期间服务会短暂停止。'}finally{$('restore-confirm').disabled=false}},'restore-error'))
$('schedule').addEventListener('submit',action(async e=>{e.preventDefault();await api('backup-schedule',{enabled:$('backup-enabled').checked,time:$('backup-time').value,daily:Number($('backup-daily').value),weekly:Number($('backup-weekly').value)});await loadBackups()},'backup-error'))
document.addEventListener('click',action(async e=>{if(e.target.matches('.copy-code')){const code=e.target.closest('.code-block').querySelector('code');await navigator.clipboard.writeText(code.textContent);e.target.textContent='已复制'}}))
window.addEventListener('beforeunload',e=>{if(S.dirty){e.preventDefault();e.returnValue=''}})
async function loadMetadata(){try{const meta=await api('metadata');for(const c of meta.categories){const option=document.createElement('option');option.value=c.id;option.textContent=c.name;option.selected=S.draft?.categories.includes(c.id)??false;$('categories').append(option)}S.metadataReady=true;$('categories').disabled=false;$('category-help').textContent='可多选已有分类'}catch(err){$('category-help').textContent='分类加载失败，保存时保留原分类';notice(err)}}
async function start(){S.identity=await request('/identity');$('backup-open').hidden=!S.identity.backupAdmin;$('blog-link').href=S.identity.blogUrl;initChat({api,request,identity:S.identity,openDraft,flush,renderMarkdown});void loadMetadata();await loadList();const id=sessionStorage.getItem(`blog-draft:${S.identity.userId}`);if(id)await openDraft(id)}
start().catch(notice)
